version: "3.7"
services:
  backend:
    image: backend
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - ${APP_PORT}:${APP_PORT}
    restart:
      ${DOCKER_RESTART_POLICY}

