FROM openjdk:17
ARG SERVICE_NAME=canteen
ENV APP_FILE ${SERVICE_NAME}-0.0.1-SNAPSHOT.jar
ENV APP_HOME /app
ENV JAVA_OPTS="-Xmx2048m -Xms1024m"
COPY /target/$APP_FILE $APP_HOME/
WORKDIR $APP_HOME
ENTRYPOINT ["sh", "-c"]
CMD ["exec java $JAVA_OPTS -jar $APP_FILE"]
